---
title: ""
format:
  pdf:
    pdf-engine: lualatex
    documentclass: article
    geometry:
      - a4paper
      - margin=1in
    mainfont: "Berkeley Mono"
    keep-tex: false
    include-in-header: |
      \usepackage{fontspec}
      \defaultfontfeatures{Ligatures=TeX}
      \setmainfont{Berkeley Mono}
      \usepackage{xcolor}
      \usepackage{longtable}
---

::: {layout="[70,30]"}
::: {#company-info}
**U.S. Graphics Company**
PO Box 32871
Phoenix, AZ 85064
billing@usgraphics.com
:::

::: {#invoice-box}
| | |
|---|---|
| **Invoice #:** | 102-AA7JHF2E |
| **Invoice Created:** | Sep 16, 2025 |
| **Invoice Due:** | Oct 15, 2025 |
:::
:::

\vspace{20pt}

**Billed To:**
European Graphics GmbH.
404 Nonexistentstrasse, Unit 2B,
70128, Stuttgart, Germany
P.O. No. 100-20358238
VAT ID 82382101

\vspace{10pt}

Order No.: TZR29K0
Checkout No.: RXL02W4WKQZK6WN4NY5K
Purchase Date: Sep 16, 2025

\vspace{10pt}

## Order TZR29K0 {.unnumbered .center}

| # | SKU | Description | | Unit Rate | Count | Amount (USD) |
|--:|:--|:--|:--|--:|--:|--:|
| 1 | FX-400 | Berkeley Mono Startup | | 495.00 | 1 | 495.00 |
| 2 | MX-004 | Berkeley Mono Standard Fonts | | 0.00 | 1 | 0.00 |
| 3 | MX-017 | Berkeley Mono Ligatures | | 0.00 | 1 | 0.00 |
| 4 | TS-024 | Berkeley Mono Standard Compiler | | 0.00 | 1 | 0.00 |
| 5 | MX-014 | Berkeley Mono Web Fonts | | 295.00 | 1 | 295.00 |
| 6 | MX-020 | Berkeley Mono App License | | 395.00 | 1 | 395.00 |
|===|===|===|===|===|===|===|
| | | | | Subtotal | | 1185.00 |
| | | | | Discount | | -90.00 |
|===|===|===|===|===|===|===|
| | | | | Net Sales Total | | 1095.00 |
| | | | | Tax | | 0.00 |
|===|===|===|===|===|===|===|
| | | | | **Total** | | **1095.00** |

\vspace{10pt}
\center Invoice Status: P A I D
\vspace{10pt}

| | | | | | | |
|---|---|---|---|---|--:|--:|
| | | | | Paid | | -1095.00 |
|===|===|===|===|===|===|===|
| | | | | **Balance** | | **0.00** |

\vspace{20pt}

Payment Method: VISA x 4242

\center ***

\center Thank you for your business.

\center U.S. Graphics Company
